#
# Profile for doing development work on full stack.
#
# Your changes will be visible live on browser reload or after restart:
#
# - Edit files in deployment/manager/
# - Edit files in keycloak/theme/
# - Mount the proxy-data volume in a new container and edit proxy configuration files
# - Change the proxy configuration to a directory mount and edit configuration files
#
version: '2.2'

volumes:
  proxy-data:
  postgresql-data:

services:

  proxy:
    extends:
      file: deploy.yml
      service: proxy
    depends_on:
      manager:
        condition: service_healthy
    volumes:
      # Store data either in host-mapped directory or a named Docker volume
      # - ${DEPLOYMENT_DIRECTORY:-../deployment}/proxy:/deployment
      - proxy-data:/deployment

  manager:
    extends:
      file: deploy.yml
      service: manager
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      # Use local deployment data in host-mapped directory for easy development. The
      # ../deployment directory is the one which will be baked into the managers image.
      - ${DEPLOYMENT_DIRECTORY:-../deployment}/manager:/deployment
    environment:
      # Always wipe and enable dev optimizations
      DEV_MODE: 'true'
      # This switch can wipe all your Manager and Keycloak data, this is the factory reset!
      SETUP_WIPE_CLEAN_INSTALL: 'true'

  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    build:
      context: ../keycloak
      dockerfile: dev.Dockerfile
    image: openremote/keycloak_dev:latest
    # Access directly if needed
    ports:
      - "8081:8080"
    volumes:
      - ../keycloak/theme:/opt/jboss/keycloak/themes/openremote
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    # Access directly if needed
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/data